name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 */12 * * *"  # Mise à jour toutes les 12 heures
  workflow_dispatch:  # Permet de l'exécuter manuellement

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
